### ISSUE TITLE
Version 0.8.2 not working on MacOs Big Sur?

### ISSUE THREAD

**Issue by andreagam** [mb21/panwriter#97]
I cannot launch Panwriter anymore on MacOs Big Sur.
The icon appears "banned" as in the applications not more compatible.
Is the new update only compatible with Monterey?
Also, I tried to downgrade to version 0.7.2 and it works, but when I close the app
and try to launch it again it automatically upgrades to the new version and doesn't open anymore.
Can anybody confirm this? Could this be fixed?
Thanks a lot,

Andrea Gambedotti

**Comment by mb21** [comment]
I haven't a Big Sur install to test myself... but that's indeed possible. I wonder why though... is it because of the [upgrade of electron builder](https://github.com/mb21/panwriter/commit/396cfa913761857d02102ad04d6472ac55d80b28) or is it because I do the build on Monterey now? Will have to investigate... possibly it's time to set up a CI/CD workflow that does the build...

**Comment by guillerodriguez** [comment]
I have 0.8.2 working on BigSur 11.6 without problems.

**Comment by mb21** [comment]
Thanks @guillerodriguez for the info!

@andreagam can you try downloading from PanWriter.com directly instead of doing the update? According [to this](https://github.com/electron-userland/electron-builder/issues/5639#issuecomment-780821515), the update may be downloading the wrong version (the Apple silicon build)... which seems it would be up to us to fix somehow by renaming the build artifacts :S

**Comment by mb21** [comment]
Released the fix, let me know if it still doesn't work...

@andreagam you'll also be pleased to know that you can disable auto-updates now, see https://github.com/mb21/panwriter#settings
